<?php
set_include_path(__DIR__ . "/RetreatOne" . PATH_SEPARATOR . get_include_path());

require_once "constants.php";
global $force_name, $phase_name, $mode_name, $event_name, $status_name, $results_name, $combatRatio_name;
$force_name = array();
$force_name[0] = "Neutral Observer";
$force_name[1] = "Laconians";
$force_name[2] = "Caprolians";

$phase_name = array();
$phase_name[1] = "<span class='rebelFace'>Laconians</span> Movement Phase";
$phase_name[2] = "<span class='rebelFace'>Laconians</span>";
$phase_name[3] = "Blue Fire Combat";
$phase_name[4] = "<span class='loyalistFace'>Caprolians</span> Movement Phase";
$phase_name[5] = "<span class='loyalistFace'>Caprolians</span>";
$phase_name[6] = "Red Fire Combat";
$phase_name[7] = "Victory";
$phase_name[8] = "<span class='rebelFace'>Laconians</span> Deploy Phase";
$phase_name[9] = "<span class='rebelFace'>Laconians</span> Mech Movement Phase";
$phase_name[10] = "<span class='rebelFace'>Laconians</span> Replacement Phase";
$phase_name[11] = "<span class='loyalistFace'>Caprolians</span> Mech Movement Phase";
$phase_name[12] = "<span class='loyalistFace'>Caprolians</span> Replacement Phase";
$phase_name[13] = "";
$phase_name[14] = "";
$phase_name[15] = "<span class='loyalistFace'>Caprolians</span> Deploy Phase";

$mode_name[17] = "";


$mode_name[3] = "Combat Setup Phase";
$mode_name[4] = "Combat Resolution Phase";
$mode_name[19] = "";

$mode_name[1] = "";
$mode_name[2] = "";

define("LACONIANS_FORCE", BLUE_FORCE);
define("CAPROLIANS_FORCE", RED_FORCE);

require_once "Battle.php";
require_once "crtTraits.php";
require_once "combatRules.php";
require_once "crt.php";
require_once "force.php";
require_once "gameRules.php";
require_once "hexagon.php";
require_once "hexpart.php";
require_once "los.php";
require_once "mapgrid.php";
require_once "moveRules.php";
require_once "prompt.php";
require_once "terrain.php";
require_once "display.php";
require_once "victory.php";
include "victoryCore.php";

// battlefforallencreek.js

// counter image values
$oneHalfImageWidth = 16;
$oneHalfImageHeight = 16;


class RetreatOne extends LandBattle
{
    /* a comment */

    /* @var MapData $mapData */
    public $mapData;
    public $mapViewer;
    public $playerData;
    /* @var Force $force */
    public $force;
    public $terrain;
    public $moveRules;
    public $combatRules;
    public $gameRules;
    public $prompt;
    public $display;
    public $victory;
    public $genTerrain = false;
    public $arg;
    public $scenario;

    public $players;

    static function getHeader($name, $playerData, $arg = false)
    {
        global $force_name;

        $playerData = array_shift($playerData);
        foreach ($playerData as $k => $v) {
            $$k = $v;
        }
        @include_once "globalHeader.php";
        @include_once "retreatOneHeader.php";
    }

    static function getView($name, $mapUrl, $player = 0, $arg = false, $scenario = false)
    {
        global $force_name;
        $player = $force_name[$player];

        @include_once "view.php";
    }

    function save()
    {
        $data = new stdClass();
        $data->arg = $this->arg;
        $data->scenario = $this->scenario;
        $data->mapData = $this->mapData;
        $data->mapViewer = $this->mapViewer;
        $data->moveRules = $this->moveRules->save();
        $data->force = $this->force;
        $data->gameRules = $this->gameRules->save();
        $data->combatRules = $this->combatRules->save();
        $data->players = $this->players;
        $data->playerData = $this->playerData;
        $data->display = $this->display;
        $data->victory = $this->victory->save();
        $data->terrainName = "terrain-" . get_class($this);
        $data->genTerrain = $this->genTerrain;
        if ($this->genTerrain) {
            $data->terrain = $this->terrain;
        }
        return $data;
    }

    function poke($event, $id, $x, $y, $user, $click)
    {

        $playerId = $this->gameRules->attackingForceId;
        if ($this->players[$this->gameRules->attackingForceId] != $user) {
            return false;
        }

        switch ($event) {
            case SELECT_MAP_EVENT:
                $mapGrid = new MapGrid($this->mapViewer[$playerId]);
                $mapGrid->setPixels($x, $y);
                return $this->gameRules->processEvent(SELECT_MAP_EVENT, MAP, $mapGrid->getHexagon(), $click);
                break;

            case SELECT_COUNTER_EVENT:
                /* fall through */
            case SELECT_SHIFT_COUNTER_EVENT:
            /* fall through */
            case COMBAT_PIN_EVENT:

            return $this->gameRules->processEvent($event, $id, $this->force->getUnitHexagon($id), $click);

                break;

            case SELECT_BUTTON_EVENT:
                $this->gameRules->processEvent(SELECT_BUTTON_EVENT, "next_phase", 0, $click);
                break;

            case KEYPRESS_EVENT:
                $this->gameRules->processEvent(KEYPRESS_EVENT, $id, null, $click);
                break;

        }
        return true;
    }

    public function init()
    {

        for($i = 0;$i < 16;$i++){
            $this->force->addUnit("xx", CAPROLIANS_FORCE, "deployBox", "multiInf.png", 3, 1, 3, false, STATUS_CAN_DEPLOY, "A", 1, 1, "caprolians", true, 'inf');
        }
        for($i = 0;$i < 4;$i++){
            $this->force->addUnit("xx", CAPROLIANS_FORCE, "deployBox", "multiMotInf.png", 4, 2, 6, false, STATUS_CAN_DEPLOY, "A", 1, 1, "caprolians", true, 'mech');
        }
        for($i = 0;$i < 4;$i++){
            $this->force->addUnit("xx", CAPROLIANS_FORCE, "deployBox", "multiMotArt.png", 3, 1, 6, false, STATUS_CAN_DEPLOY, "A", 1, 5, "caprolians", true, 'mech');
        }
        for($i = 0;$i < 4;$i++){
            $this->force->addUnit("xx", CAPROLIANS_FORCE, "deployBox", "multiArmor.png", 4, 2, 4, false, STATUS_CAN_DEPLOY, "A", 1, 1, "caprolians", true, 'mech');
        }
        for($i = 0;$i < 3;$i++){
            $this->force->addUnit("xx", CAPROLIANS_FORCE, "deployBox", "multiRecon.png", 2, 1, 6, false, STATUS_CAN_DEPLOY, "A", 1, 1, "caprolians", true, 'mech');
        }

        for($i = 0;$i < 12;$i++){
            $this->force->addUnit("xx", LACONIANS_FORCE, "deployBox", "multiMotInf.png", 4, 2, 6, false, STATUS_CAN_DEPLOY, "B", 1, 1, "laconians", true, "mech");
        }
        for($i = 0;$i < 4;$i++){
            $this->force->addUnit("xx", LACONIANS_FORCE, "deployBox", "multiMotArt.png", 4, 2, 6, false, STATUS_CAN_DEPLOY, "B", 1, 5, "laconians", true, "mech");
        }
        for($i = 0;$i < 4;$i++){
            $this->force->addUnit("xx", LACONIANS_FORCE, "deployBox", "multiArmor.png", 4, 2, 5, false, STATUS_CAN_DEPLOY, "B", 1, 1, "laconians", true, "mech");
        }
        for($i = 0;$i < 2;$i++){
            $this->force->addUnit("xx", LACONIANS_FORCE, "deployBox", "multiArmor.png", 6, 3, 3, false, STATUS_CAN_DEPLOY, "B", 1, 1, "laconians", true, "mech");
        }
        for($i = 0;$i < 4;$i++){
            $this->force->addUnit("xx", LACONIANS_FORCE, "deployBox", "multiRecon.png", 2, 1, 6, false, STATUS_CAN_DEPLOY, "B", 1, 1, "laconians", true, "mech");
        }
    }

    function __construct($data = null, $arg = false, $scenario = false, $game = false)
    {

        $this->mapData = MapData::getInstance();
        if ($data) {
            $this->arg = $data->arg;
            $this->scenario = $data->scenario;
            $this->genTerrain = false;
            $this->victory = new Victory("TMCW/RetreatOne/retreatOneVictoryCore.php", $data);
            $this->display = new Display($data->display);
            $this->mapData->init($data->mapData);
            $this->mapViewer = array(new MapViewer($data->mapViewer[0]), new MapViewer($data->mapViewer[1]), new MapViewer($data->mapViewer[2]));
            $this->force = new Force($data->force);
            $this->terrain = new Terrain($data->terrain);
            $this->moveRules = new MoveRules($this->force, $this->terrain, $data->moveRules);
            $this->combatRules = new CombatRules($this->force, $this->terrain, $data->combatRules);
            $this->gameRules = new GameRules($this->moveRules, $this->combatRules, $this->force, $this->display, $data->gameRules);
            $this->prompt = new Prompt($this->gameRules, $this->moveRules, $this->combatRules, $this->force, $this->terrain);
            $this->prompt = new Prompt($this->gameRules, $this->moveRules, $this->combatRules, $this->force, $this->terrain);
            $this->players = $data->players;
            $this->playerData = $data->playerData;
        } else {
            $this->arg = $arg;
            $this->scenario = $scenario;
            $this->genTerrain = true;
            $this->victory = new Victory("TMCW/RetreatOne/retreatOneVictoryCore.php");
            if ($scenario->supplyLen) {
                $this->victory->setSupplyLen($scenario->supplyLen);
            }
            $this->display = new Display();
            $this->mapData->setData(60, 30, "js/Retreat1Small.png");

            $this->mapViewer = array(new MapViewer(), new MapViewer(), new MapViewer());
            $this->force = new Force();
            $this->terrain = new Terrain();
            $this->moveRules = new MoveRules($this->force, $this->terrain);
            if ($scenario && $scenario->supply === true) {
                $this->moveRules->enterZoc = 2;
                $this->moveRules->exitZoc = 1;
                $this->moveRules->noZocZocOneHex = true;
            } else {
                $this->moveRules->enterZoc = "stop";
                $this->moveRules->exitZoc = 0;
                $this->moveRules->noZocZocOneHex = false;
            }
            $this->combatRules = new CombatRules($this->force, $this->terrain);
            $this->gameRules = new GameRules($this->moveRules, $this->combatRules, $this->force, $this->display);
            $this->prompt = new Prompt($this->gameRules, $this->moveRules, $this->combatRules, $this->force, $this->terrain);
            $this->players = array("", "", "");
            $this->playerData = new stdClass();
            for ($player = 0; $player <= 2; $player++) {
                $this->playerData->${player} = new stdClass();
                $this->playerData->${player}->mapWidth = "auto";
                $this->playerData->${player}->mapHeight = "auto";
                $this->playerData->${player}->unitSize = "32px";
                $this->playerData->${player}->unitFontSize = "12px";
                $this->playerData->${player}->unitMargin = "-21px";
            }

            for($player = 0;$player < 3;$player++){
                $this->mapViewer[$player]->setData(52.72 , 85.37278430506997, // originX, originY
                    28.457594768356657, 28.457594768356657, // top hexagon height, bottom hexagon height
                    16.43, 32.86// hexagon edge width, hexagon center width
                );
            }
            // game data
            $this->gameRules->setMaxTurn(15);

            $this->gameRules->setInitialPhaseMode(RED_DEPLOY_PHASE, DEPLOY_MODE);
            $this->gameRules->attackingForceId = RED_FORCE; /* object oriented! */
            $this->gameRules->defendingForceId = BLUE_FORCE; /* object oriented! */
            $this->force->setAttackingForceId($this->gameRules->attackingForceId); /* so object oriented */




            $this->gameRules->addPhaseChange(RED_DEPLOY_PHASE, BLUE_DEPLOY_PHASE, DEPLOY_MODE, BLUE_FORCE, RED_FORCE, false);
            $this->gameRules->addPhaseChange(BLUE_DEPLOY_PHASE, BLUE_MOVE_PHASE, MOVING_MODE, BLUE_FORCE, RED_FORCE, false);
            $this->gameRules->addPhaseChange(BLUE_MOVE_PHASE, BLUE_COMBAT_PHASE, COMBAT_SETUP_MODE, BLUE_FORCE, RED_FORCE, false);
            $this->gameRules->addPhaseChange(BLUE_COMBAT_PHASE, BLUE_MECH_PHASE, MOVING_MODE, BLUE_FORCE, RED_FORCE, false);
            $this->gameRules->addPhaseChange(BLUE_MECH_PHASE, RED_MOVE_PHASE, MOVING_MODE, RED_FORCE, BLUE_FORCE, false);
            $this->gameRules->addPhaseChange(RED_MOVE_PHASE, RED_COMBAT_PHASE, COMBAT_SETUP_MODE, RED_FORCE, BLUE_FORCE, false);
            $this->gameRules->addPhaseChange(RED_COMBAT_PHASE, RED_MECH_PHASE, MOVING_MODE, RED_FORCE, BLUE_FORCE, false);
            $this->gameRules->addPhaseChange(RED_MECH_PHASE, BLUE_MOVE_PHASE, MOVING_MODE, BLUE_FORCE, RED_FORCE, true);
            // unit terrain data----------------------------------------

            // code, name, displayName, letter, entranceCost, traverseCost, combatEffect, is Exclusive
            $this->terrain->addTerrainFeature("offmap", "offmap", "o", 1, 0, 0, true);
            $this->terrain->addTerrainFeature("blocked", "blocked", "b", 1, 0, 0, true);
            $this->terrain->addTerrainFeature("clear", "clear", "c", 1, 0, 0, true);
            $this->terrain->addTerrainFeature("road", "road", "r", .5, 0, 0, false);
            $this->terrain->addTerrainFeature("secondaryroad", "secondaryroad", "r", .75, 0, 0, false);
            $this->terrain->addTerrainFeature("trail", "trail", "r", 1, 0, 0, false);
            $this->terrain->addTerrainFeature("fortified", "fortified", "h", 1, 0, 1, true);
            $this->terrain->addTerrainFeature("town", "town", "t", 0, 0, 0, false);
            $this->terrain->addTerrainFeature("forest", "forest", "f", 2, 0, 1, true);
            $this->terrain->addTerrainFeature("roughone", "roughone", "g", 2, 0, 2, true);
            $this->terrain->addTerrainFeature("roughtwo", "roughtwo", "g", 3, 0, 2, true);
            $this->terrain->addTerrainFeature("swamp", "swamp", "f", 3, 0, 1, true);
            $this->terrain->addTerrainFeature("river", "Martian River", "v", 0, 1, 1, true);
            $this->terrain->addTerrainFeature("wadi", "wadi", "w", 0, 1, 1, false);
            $this->terrain->addAltEntranceCost("roughone", "mech", 6);
            $this->terrain->addAltEntranceCost("roughtwo", "mech", "blocked");

            /* handle fort's in crtTraits */

            /*
             * First put clear everywhere, hexes and hex sides
             */
            for ($col = 100; $col <= 6000; $col += 100) {
                for ($row = 1; $row <= 30; $row++) {
                    $this->terrain->addTerrain($row + $col, LOWER_LEFT_HEXSIDE, "clear");
                    $this->terrain->addTerrain($row + $col, UPPER_LEFT_HEXSIDE, "clear");
                    $this->terrain->addTerrain($row + $col, BOTTOM_HEXSIDE, "clear");
                    $this->terrain->addTerrain($row + $col, HEXAGON_CENTER, "clear");

                }
            }


            /*
             * Next put terrain like rough and forest because they are exclusive and will cancel what else is there.
             */
            $this->terrain->addTerrain(1205 ,1 , "roughone");
            $this->terrain->addTerrain(1305 ,1 , "roughone");
            $this->terrain->addTerrain(1306 ,1 , "roughone");
            $this->terrain->addTerrain(1206 ,1 , "roughone");
            $this->terrain->addTerrain(1506 ,1 , "roughtwo");
            $this->terrain->addTerrain(1605 ,1 , "roughtwo");
            $this->terrain->addTerrain(1604 ,1 , "roughtwo");
            $this->terrain->addTerrain(1704 ,1 , "roughtwo");
            $this->terrain->addTerrain(1705 ,1 , "roughtwo");
            $this->terrain->addTerrain(1706 ,1 , "roughtwo");
            $this->terrain->addTerrain(1907 ,1 , "roughtwo");
            $this->terrain->addTerrain(1908 ,1 , "roughtwo");
            $this->terrain->addTerrain(2007 ,1 , "roughtwo");
            $this->terrain->addTerrain(207 ,1 , "roughtwo");
            $this->terrain->addTerrain(208 ,1 , "roughtwo");
            $this->terrain->addTerrain(308 ,1 , "roughtwo");
            $this->terrain->addTerrain(309 ,1 , "roughtwo");
            $this->terrain->addTerrain(1106 ,1 , "roughone");
            $this->terrain->addTerrain(1107 ,1 , "roughone");
            $this->terrain->addTerrain(1111 ,1 , "town");
            $this->terrain->addReinforceZone(1111,'A');
            $this->terrain->addTerrain(1004 ,1 , "town");
            $this->terrain->addReinforceZone(1004,'A');
            $this->terrain->addTerrain(1105 ,1 , "town");
            $this->terrain->addTerrain(116 ,1 , "town");
            $this->terrain->addTerrain(407 ,1 , "roughone");
            $this->terrain->addTerrain(307 ,1 , "roughone");
            $this->terrain->addTerrain(406 ,1 , "roughone");
            $this->terrain->addTerrain(506 ,1 , "roughone");
            $this->terrain->addTerrain(506 ,1 , "secondaryroad");
            $this->terrain->addTerrain(405 ,1 , "roughone");
            $this->terrain->addTerrain(405 ,1 , "secondaryroad");
            $this->terrain->addTerrain(306 ,1 , "roughone");
            $this->terrain->addTerrain(306 ,1 , "secondaryroad");
            $this->terrain->addTerrain(305 ,1 , "roughone");
            $this->terrain->addTerrain(205 ,1 , "roughone");
            $this->terrain->addTerrain(204 ,1 , "roughone");
            $this->terrain->addTerrain(105 ,1 , "roughone");
            $this->terrain->addTerrain(106 ,1 , "roughone");
            $this->terrain->addTerrain(206 ,1 , "roughone");
            $this->terrain->addTerrain(206 ,1 , "secondaryroad");
            $this->terrain->addTerrain(507 ,1 , "roughone");
            $this->terrain->addTerrain(508 ,1 , "roughone");
            $this->terrain->addTerrain(408 ,1 , "roughone");
            $this->terrain->addTerrain(108 ,1 , "roughone");
            $this->terrain->addTerrain(109 ,1 , "roughone");
            $this->terrain->addTerrain(209 ,1 , "roughone");
            $this->terrain->addTerrain(409 ,1 , "roughone");
            $this->terrain->addTerrain(509 ,1 , "roughone");
            $this->terrain->addTerrain(410 ,1 , "roughone");
            $this->terrain->addTerrain(110 ,1 , "roughone");
            $this->terrain->addTerrain(411 ,1 , "roughone");
            $this->terrain->addTerrain(412 ,1 , "roughone");
            $this->terrain->addTerrain(313 ,1 , "roughone");
            $this->terrain->addTerrain(413 ,1 , "roughone");
            $this->terrain->addTerrain(314 ,1 , "roughone");
            $this->terrain->addTerrain(213 ,1 , "roughone");
            $this->terrain->addTerrain(114 ,1 , "roughone");
            $this->terrain->addTerrain(214 ,1 , "roughone");
            $this->terrain->addTerrain(115 ,1 , "roughone");
            $this->terrain->addTerrain(1116 ,1 , "roughone");
            $this->terrain->addTerrain(1115 ,1 , "roughone");
            $this->terrain->addTerrain(1215 ,1 , "roughone");
            $this->terrain->addTerrain(1114 ,1 , "roughone");
            $this->terrain->addTerrain(1213 ,1 , "roughone");
            $this->terrain->addTerrain(1313 ,1 , "roughone");
            $this->terrain->addTerrain(1208 ,1 , "roughone");
            $this->terrain->addTerrain(1308 ,1 , "roughone");
            $this->terrain->addTerrain(1407 ,1 , "roughone");
            $this->terrain->addTerrain(1406 ,1 , "roughone");
            $this->terrain->addTerrain(1405 ,1 , "roughone");
            $this->terrain->addTerrain(1505 ,1 , "roughone");
            $this->terrain->addTerrain(1504 ,1 , "roughone");
            $this->terrain->addTerrain(1603 ,1 , "roughone");
            $this->terrain->addTerrain(1703 ,1 , "roughone");
            $this->terrain->addTerrain(1803 ,1 , "roughone");
            $this->terrain->addTerrain(1804 ,1 , "roughone");
            $this->terrain->addTerrain(1904 ,1 , "roughone");
            $this->terrain->addTerrain(1805 ,1 , "roughone");
            $this->terrain->addTerrain(1906 ,1 , "roughone");
            $this->terrain->addTerrain(1906 ,1 , "trail");
            $this->terrain->addTerrain(1806 ,1 , "roughone");
            $this->terrain->addTerrain(1806 ,1 , "trail");
            $this->terrain->addTerrain(1707 ,1 , "roughone");
            $this->terrain->addTerrain(1707 ,1 , "trail");
            $this->terrain->addTerrain(1606 ,1 , "roughone");
            $this->terrain->addTerrain(1507 ,1 , "roughone");
            $this->terrain->addTerrain(1508 ,1 , "roughone");
            $this->terrain->addTerrain(1408 ,1 , "roughone");
            $this->terrain->addTerrain(1309 ,1 , "roughone");
            $this->terrain->addTerrain(1807 ,1 , "roughone");
            $this->terrain->addTerrain(1808 ,1 , "roughone");
            $this->terrain->addTerrain(1809 ,1 , "roughone");
            $this->terrain->addTerrain(1909 ,1 , "roughone");
            $this->terrain->addTerrain(1910 ,1 , "roughone");
            $this->terrain->addTerrain(2006 ,1 , "roughone");
            $this->terrain->addTerrain(2008 ,1 , "roughone");
            $this->terrain->addTerrain(2108 ,1 , "roughone");
            $this->terrain->addTerrain(2107 ,1 , "roughone");
            $this->terrain->addTerrain(2207 ,1 , "roughone");
            $this->terrain->addTerrain(2208 ,1 , "roughone");
            $this->terrain->addTerrain(2109 ,1 , "roughone");
            $this->terrain->addTerrain(2209 ,1 , "roughone");
            $this->terrain->addTerrain(2110 ,1 , "roughone");
            $this->terrain->addTerrain(3510 ,1 , "roughone");
            $this->terrain->addTerrain(3410 ,1 , "roughone");
            $this->terrain->addTerrain(3511 ,1 , "roughone");
            $this->terrain->addTerrain(3610 ,1 , "roughone");
            $this->terrain->addTerrain(3512 ,1 , "roughone");
            $this->terrain->addTerrain(3411 ,1 , "roughone");
            $this->terrain->addTerrain(3412 ,1 , "roughone");
            $this->terrain->addTerrain(3413 ,1 , "roughone");
            $this->terrain->addTerrain(3513 ,1 , "roughone");
            $this->terrain->addTerrain(3613 ,1 , "roughone");
            $this->terrain->addTerrain(3714 ,1 , "roughone");
            $this->terrain->addTerrain(3715 ,1 , "roughone");
            $this->terrain->addTerrain(3414 ,1 , "roughone");
            $this->terrain->addTerrain(3716 ,1 , "roughone");
            $this->terrain->addTerrain(3616 ,1 , "roughone");
            $this->terrain->addTerrain(3517 ,1 , "roughone");
            $this->terrain->addTerrain(3416 ,1 , "roughone");
            $this->terrain->addTerrain(3415 ,1 , "roughone");
            $this->terrain->addTerrain(3417 ,1 , "roughone");
            $this->terrain->addTerrain(3417 ,1 , "secondaryroad");
            $this->terrain->addTerrain(3317 ,1 , "roughone");
            $this->terrain->addTerrain(3317 ,1 , "secondaryroad");
            $this->terrain->addTerrain(3318 ,1 , "roughone");
            $this->terrain->addTerrain(3217 ,1 , "roughone");
            $this->terrain->addTerrain(3118 ,1 , "roughone");
            $this->terrain->addTerrain(3017 ,1 , "roughone");
            $this->terrain->addTerrain(2917 ,1 , "roughone");
            $this->terrain->addTerrain(2817 ,1 , "roughone");
            $this->terrain->addTerrain(2816 ,1 , "roughone");
            $this->terrain->addTerrain(2717 ,1 , "roughone");
            $this->terrain->addTerrain(2716 ,1 , "roughone");
            $this->terrain->addTerrain(2815 ,1 , "roughone");
            $this->terrain->addTerrain(2814 ,1 , "roughone");
            $this->terrain->addTerrain(2715 ,1 , "roughone");
            $this->terrain->addTerrain(2616 ,1 , "roughone");
            $this->terrain->addTerrain(2517 ,1 , "roughone");
            $this->terrain->addTerrain(3018 ,1 , "roughone");
            $this->terrain->addTerrain(3119 ,1 , "roughone");
            $this->terrain->addTerrain(3218 ,1 , "roughone");
            $this->terrain->addTerrain(3219 ,1 , "roughone");
            $this->terrain->addTerrain(3120 ,1 , "roughone");
            $this->terrain->addTerrain(3019 ,1 , "roughone");
            $this->terrain->addTerrain(2920 ,1 , "roughone");
            $this->terrain->addTerrain(2820 ,1 , "roughone");
            $this->terrain->addTerrain(2821 ,1 , "roughone");
            $this->terrain->addTerrain(2922 ,1 , "roughone");
            $this->terrain->addTerrain(3022 ,1 , "roughone");
            $this->terrain->addTerrain(3123 ,1 , "roughone");
            $this->terrain->addTerrain(3222 ,1 , "roughone");
            $this->terrain->addTerrain(3023 ,1 , "roughone");
            $this->terrain->addTerrain(2923 ,1 , "roughone");
            $this->terrain->addTerrain(2924 ,1 , "roughone");
            $this->terrain->addTerrain(2823 ,1 , "roughone");
            $this->terrain->addTerrain(2822 ,1 , "roughone");
            $this->terrain->addTerrain(2723 ,1 , "roughone");
            $this->terrain->addTerrain(2722 ,1 , "roughone");
            $this->terrain->addTerrain(2721 ,1 , "roughone");
            $this->terrain->addTerrain(2620 ,1 , "roughone");
            $this->terrain->addTerrain(2621 ,1 , "roughone");
            $this->terrain->addTerrain(2518 ,1 , "roughone");
            $this->terrain->addTerrain(2519 ,1 , "roughone");
            $this->terrain->addTerrain(2520 ,1 , "roughone");
            $this->terrain->addTerrain(2521 ,1 , "roughone");
            $this->terrain->addTerrain(2418 ,1 , "roughone");
            $this->terrain->addTerrain(2419 ,1 , "roughone");
            $this->terrain->addTerrain(2420 ,1 , "roughone");
            $this->terrain->addTerrain(2421 ,1 , "roughone");
            $this->terrain->addTerrain(2319 ,1 , "roughone");
            $this->terrain->addTerrain(2322 ,1 , "roughone");
            $this->terrain->addTerrain(2623 ,1 , "roughone");
            $this->terrain->addTerrain(2524 ,1 , "roughone");
            $this->terrain->addTerrain(2424 ,1 , "roughone");
            $this->terrain->addTerrain(2324 ,1 , "roughone");
            $this->terrain->addTerrain(2223 ,1 , "roughone");
            $this->terrain->addTerrain(2222 ,1 , "roughone");
            $this->terrain->addTerrain(2123 ,1 , "roughone");
            $this->terrain->addTerrain(2123 ,1 , "trail");
            $this->terrain->addTerrain(2122 ,1 , "roughone");
            $this->terrain->addTerrain(2122 ,1 , "trail");
            $this->terrain->addTerrain(2121 ,1 , "roughone");
            $this->terrain->addTerrain(2220 ,1 , "roughone");
            $this->terrain->addTerrain(2120 ,1 , "roughone");
            $this->terrain->addTerrain(2021 ,1 , "roughone");
            $this->terrain->addTerrain(2022 ,1 , "roughone");
            $this->terrain->addTerrain(2023 ,1 , "roughone");
            $this->terrain->addTerrain(2024 ,1 , "roughone");
            $this->terrain->addTerrain(1924 ,1 , "roughone");
            $this->terrain->addTerrain(1925 ,1 , "roughone");
            $this->terrain->addTerrain(1922 ,1 , "roughone");
            $this->terrain->addTerrain(1921 ,1 , "roughone");
            $this->terrain->addTerrain(1820 ,1 , "roughone");
            $this->terrain->addTerrain(1821 ,1 , "roughone");
            $this->terrain->addTerrain(1721 ,1 , "roughone");
            $this->terrain->addTerrain(1720 ,1 , "roughone");
            $this->terrain->addTerrain(1620 ,1 , "roughone");
            $this->terrain->addTerrain(1621 ,1 , "roughone");
            $this->terrain->addTerrain(1521 ,1 , "roughone");
            $this->terrain->addTerrain(1522 ,1 , "roughone");
            $this->terrain->addTerrain(1421 ,1 , "roughone");
            $this->terrain->addTerrain(1422 ,1 , "roughone");
            $this->terrain->addTerrain(1323 ,1 , "roughone");
            $this->terrain->addTerrain(1423 ,1 , "roughone");
            $this->terrain->addTerrain(1324 ,1 , "roughone");
            $this->terrain->addTerrain(1424 ,1 , "roughone");
            $this->terrain->addTerrain(1325 ,1 , "roughone");
            $this->terrain->addTerrain(1525 ,1 , "roughone");
            $this->terrain->addTerrain(1624 ,1 , "roughone");
            $this->terrain->addTerrain(1725 ,1 , "roughone");
            $this->terrain->addTerrain(1625 ,1 , "roughone");
            $this->terrain->addTerrain(1825 ,1 , "roughone");
            $this->terrain->addTerrain(1726 ,1 , "roughone");
            $this->terrain->addTerrain(821 ,1 , "roughone");
            $this->terrain->addTerrain(722 ,1 , "roughone");
            $this->terrain->addTerrain(822 ,1 , "roughone");
            $this->terrain->addTerrain(723 ,1 , "roughone");
            $this->terrain->addTerrain(923 ,1 , "roughone");
            $this->terrain->addTerrain(1022 ,1 , "roughone");
            $this->terrain->addTerrain(1123 ,1 , "roughone");
            $this->terrain->addTerrain(1124 ,1 , "roughone");
            $this->terrain->addTerrain(1023 ,1 , "roughone");
            $this->terrain->addTerrain(924 ,1 , "roughone");
            $this->terrain->addTerrain(925 ,1 , "roughone");
            $this->terrain->addTerrain(1024 ,1 , "roughone");
            $this->terrain->addTerrain(1125 ,1 , "roughone");
            $this->terrain->addTerrain(1025 ,1 , "roughone");
            $this->terrain->addTerrain(825 ,1 , "roughone");
            $this->terrain->addTerrain(724 ,1 , "roughone");
            $this->terrain->addTerrain(624 ,1 , "roughone");
            $this->terrain->addTerrain(524 ,1 , "roughone");
            $this->terrain->addTerrain(523 ,1 , "roughone");
            $this->terrain->addTerrain(525 ,1 , "roughone");
            $this->terrain->addTerrain(526 ,1 , "roughone");
            $this->terrain->addTerrain(726 ,1 , "roughone");
            $this->terrain->addTerrain(826 ,1 , "roughone");
            $this->terrain->addTerrain(927 ,1 , "roughone");
            $this->terrain->addTerrain(928 ,1 , "roughone");
            $this->terrain->addTerrain(827 ,1 , "roughone");
            $this->terrain->addTerrain(727 ,1 , "roughone");
            $this->terrain->addTerrain(426 ,1 , "roughone");
            $this->terrain->addTerrain(426 ,1 , "secondaryroad");
            $this->terrain->addTerrain(527 ,1 , "roughone");
            $this->terrain->addTerrain(527 ,1 , "secondaryroad");
            $this->terrain->addTerrain(627 ,1 , "roughone");
            $this->terrain->addTerrain(627 ,1 , "secondaryroad");
            $this->terrain->addTerrain(728 ,1 , "roughone");
            $this->terrain->addTerrain(728 ,1 , "secondaryroad");
            $this->terrain->addTerrain(828 ,1 , "roughone");
            $this->terrain->addTerrain(828 ,1 , "secondaryroad");
            $this->terrain->addTerrain(929 ,1 , "roughone");
            $this->terrain->addTerrain(929 ,1 , "secondaryroad");
            $this->terrain->addTerrain(930 ,1 , "roughone");
            $this->terrain->addTerrain(829 ,1 , "roughone");
            $this->terrain->addTerrain(729 ,1 , "roughone");
            $this->terrain->addTerrain(628 ,1 , "roughone");
            $this->terrain->addTerrain(528 ,1 , "roughone");
            $this->terrain->addTerrain(528 ,1 , "secondaryroad");
            $this->terrain->addTerrain(327 ,1 , "roughone");
            $this->terrain->addTerrain(328 ,1 , "roughone");
            $this->terrain->addTerrain(529 ,1 , "roughone");
            $this->terrain->addTerrain(529 ,1 , "secondaryroad");
            $this->terrain->addTerrain(429 ,1 , "roughone");
            $this->terrain->addTerrain(429 ,1 , "secondaryroad");
            $this->terrain->addTerrain(329 ,1 , "roughone");
            $this->terrain->addTerrain(329 ,1 , "secondaryroad");
            $this->terrain->addTerrain(229 ,1 , "roughone");
            $this->terrain->addTerrain(229 ,1 , "secondaryroad");
            $this->terrain->addTerrain(228 ,1 , "roughone");
            $this->terrain->addTerrain(129 ,1 , "roughone");
            $this->terrain->addTerrain(128 ,1 , "roughone");
            $this->terrain->addTerrain(127 ,1 , "roughone");
            $this->terrain->addTerrain(126 ,1 , "roughone");
            $this->terrain->addTerrain(225 ,1 , "roughone");
            $this->terrain->addTerrain(130 ,1 , "roughone");
            $this->terrain->addTerrain(230 ,1 , "roughone");
            $this->terrain->addTerrain(230 ,1 , "secondaryroad");
            $this->terrain->addTerrain(330 ,1 , "roughone");
            $this->terrain->addTerrain(430 ,1 , "roughone");
            $this->terrain->addTerrain(530 ,1 , "roughone");
            $this->terrain->addTerrain(630 ,1 , "roughone");
            $this->terrain->addTerrain(730 ,1 , "roughone");
            $this->terrain->addTerrain(830 ,1 , "roughone");
            $this->terrain->addTerrain(3627 ,1 , "roughone");
            $this->terrain->addTerrain(3528 ,1 , "roughone");
            $this->terrain->addTerrain(3427 ,1 , "roughone");
            $this->terrain->addTerrain(3527 ,1 , "roughone");
            $this->terrain->addTerrain(3426 ,1 , "roughone");
            $this->terrain->addTerrain(4030 ,1 , "roughone");
            $this->terrain->addTerrain(4029 ,1 , "roughone");
            $this->terrain->addTerrain(4028 ,1 , "roughone");
            $this->terrain->addTerrain(4128 ,1 , "roughone");
            $this->terrain->addTerrain(4127 ,1 , "roughone");
            $this->terrain->addTerrain(4226 ,1 , "roughone");
            $this->terrain->addTerrain(4326 ,1 , "roughone");
            $this->terrain->addTerrain(4227 ,1 , "roughone");
            $this->terrain->addTerrain(4228 ,1 , "roughone");
            $this->terrain->addTerrain(4229 ,1 , "roughone");
            $this->terrain->addTerrain(4230 ,1 , "roughone");
            $this->terrain->addTerrain(5224 ,1 , "roughone");
            $this->terrain->addTerrain(5125 ,1 , "roughone");
            $this->terrain->addTerrain(5124 ,1 , "roughone");
            $this->terrain->addTerrain(5024 ,1 , "roughone");
            $this->terrain->addTerrain(5025 ,1 , "roughone");
            $this->terrain->addTerrain(4925 ,1 , "roughone");
            $this->terrain->addTerrain(4824 ,1 , "roughone");
            $this->terrain->addTerrain(4725 ,1 , "roughone");
            $this->terrain->addTerrain(4624 ,1 , "roughone");
            $this->terrain->addTerrain(4524 ,1 , "roughone");
            $this->terrain->addTerrain(4623 ,1 , "roughone");
            $this->terrain->addTerrain(4523 ,1 , "roughone");
            $this->terrain->addTerrain(4522 ,1 , "roughone");
            $this->terrain->addTerrain(4622 ,1 , "roughone");
            $this->terrain->addTerrain(4621 ,1 , "roughone");
            $this->terrain->addTerrain(4521 ,1 , "roughone");
            $this->terrain->addTerrain(4520 ,1 , "roughone");
            $this->terrain->addTerrain(4420 ,1 , "roughone");
            $this->terrain->addTerrain(4419 ,1 , "roughone");
            $this->terrain->addTerrain(4721 ,1 , "roughone");
            $this->terrain->addTerrain(4821 ,1 , "roughone");
            $this->terrain->addTerrain(4822 ,1 , "roughone");
            $this->terrain->addTerrain(4922 ,1 , "roughone");
            $this->terrain->addTerrain(4923 ,1 , "roughone");
            $this->terrain->addTerrain(5022 ,1 , "roughone");
            $this->terrain->addTerrain(5021 ,1 , "roughone");
            $this->terrain->addTerrain(5122 ,1 , "roughone");
            $this->terrain->addTerrain(5123 ,1 , "roughone");
            $this->terrain->addTerrain(5222 ,1 , "roughone");
            $this->terrain->addTerrain(5417 ,1 , "roughone");
            $this->terrain->addTerrain(5418 ,1 , "roughone");
            $this->terrain->addTerrain(5518 ,1 , "roughone");
            $this->terrain->addTerrain(5519 ,1 , "roughone");
            $this->terrain->addTerrain(5419 ,1 , "roughone");
            $this->terrain->addTerrain(5619 ,1 , "roughone");
            $this->terrain->addTerrain(5620 ,1 , "roughone");
            $this->terrain->addTerrain(5420 ,1 , "roughone");
            $this->terrain->addTerrain(5421 ,1 , "roughone");
            $this->terrain->addTerrain(5522 ,1 , "roughone");
            $this->terrain->addTerrain(5721 ,1 , "roughone");
            $this->terrain->addTerrain(5722 ,1 , "roughone");
            $this->terrain->addTerrain(5622 ,1 , "roughone");
            $this->terrain->addTerrain(5723 ,1 , "roughone");
            $this->terrain->addTerrain(5623 ,1 , "roughone");
            $this->terrain->addTerrain(5623 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5524 ,1 , "roughone");
            $this->terrain->addTerrain(5424 ,1 , "roughone");
            $this->terrain->addTerrain(5923 ,1 , "roughone");
            $this->terrain->addTerrain(5823 ,1 , "roughone");
            $this->terrain->addTerrain(5724 ,1 , "roughone");
            $this->terrain->addTerrain(5724 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5624 ,1 , "roughone");
            $this->terrain->addTerrain(5525 ,1 , "roughone");
            $this->terrain->addTerrain(5526 ,1 , "roughone");
            $this->terrain->addTerrain(5625 ,1 , "roughone");
            $this->terrain->addTerrain(5725 ,1 , "roughone");
            $this->terrain->addTerrain(5924 ,1 , "roughone");
            $this->terrain->addTerrain(6023 ,1 , "roughone");
            $this->terrain->addTerrain(6024 ,1 , "roughone");
            $this->terrain->addTerrain(5626 ,1 , "roughone");
            $this->terrain->addTerrain(5527 ,1 , "roughone");
            $this->terrain->addTerrain(5627 ,1 , "roughone");
            $this->terrain->addTerrain(5727 ,1 , "roughone");
            $this->terrain->addTerrain(5826 ,1 , "roughone");
            $this->terrain->addTerrain(5926 ,1 , "roughone");
            $this->terrain->addTerrain(6026 ,1 , "roughone");
            $this->terrain->addTerrain(5927 ,1 , "roughone");
            $this->terrain->addTerrain(5628 ,1 , "roughone");
            $this->terrain->addTerrain(5729 ,1 , "roughone");
            $this->terrain->addTerrain(5829 ,1 , "roughone");
            $this->terrain->addTerrain(5830 ,1 , "roughone");
            $this->terrain->addTerrain(5730 ,1 , "roughone");
            $this->terrain->addTerrain(5213 ,1 , "roughone");
            $this->terrain->addTerrain(5113 ,1 , "roughone");
            $this->terrain->addTerrain(5012 ,1 , "roughone");
            $this->terrain->addTerrain(5013 ,1 , "roughone");
            $this->terrain->addTerrain(4913 ,1 , "roughone");
            $this->terrain->addTerrain(4812 ,1 , "roughone");
            $this->terrain->addTerrain(4914 ,1 , "roughone");
            $this->terrain->addTerrain(4813 ,1 , "roughone");
            $this->terrain->addTerrain(4713 ,1 , "roughone");
            $this->terrain->addTerrain(4613 ,1 , "roughone");
            $this->terrain->addTerrain(4612 ,1 , "roughone");
            $this->terrain->addTerrain(4512 ,1 , "roughone");
            $this->terrain->addTerrain(4513 ,1 , "roughone");
            $this->terrain->addTerrain(4514 ,1 , "roughone");
            $this->terrain->addTerrain(4414 ,1 , "roughone");
            $this->terrain->addTerrain(4413 ,1 , "roughone");
            $this->terrain->addTerrain(4412 ,1 , "roughone");
            $this->terrain->addTerrain(4411 ,1 , "roughone");
            $this->terrain->addTerrain(4311 ,1 , "roughone");
            $this->terrain->addTerrain(4312 ,1 , "roughone");
            $this->terrain->addTerrain(4313 ,1 , "roughone");
            $this->terrain->addTerrain(4314 ,1 , "roughone");
            $this->terrain->addTerrain(4315 ,1 , "roughone");
            $this->terrain->addTerrain(4214 ,1 , "roughone");
            $this->terrain->addTerrain(4213 ,1 , "roughone");
            $this->terrain->addTerrain(4212 ,1 , "roughone");
            $this->terrain->addTerrain(4211 ,1 , "roughone");
            $this->terrain->addTerrain(4112 ,1 , "roughone");
            $this->terrain->addTerrain(4113 ,1 , "roughone");
            $this->terrain->addTerrain(4114 ,1 , "roughone");
            $this->terrain->addTerrain(4115 ,1 , "roughone");
            $this->terrain->addTerrain(4015 ,1 , "roughone");
            $this->terrain->addTerrain(4014 ,1 , "roughone");
            $this->terrain->addTerrain(4013 ,1 , "roughone");
            $this->terrain->addTerrain(3914 ,1 , "roughone");
            $this->terrain->addTerrain(3915 ,1 , "roughone");
            $this->terrain->addTerrain(3916 ,1 , "roughone");
            $this->terrain->addTerrain(3812 ,1 , "roughone");
            $this->terrain->addTerrain(3912 ,1 , "roughone");
            $this->terrain->addTerrain(823 ,1 , "roughtwo");
            $this->terrain->addTerrain(824 ,1 , "roughtwo");
            $this->terrain->addTerrain(725 ,1 , "roughtwo");
            $this->terrain->addTerrain(625 ,1 , "roughtwo");
            $this->terrain->addTerrain(626 ,1 , "roughtwo");
            $this->terrain->addTerrain(427 ,1 , "roughtwo");
            $this->terrain->addTerrain(428 ,1 , "roughtwo");
            $this->terrain->addTerrain(1524 ,1 , "roughtwo");
            $this->terrain->addTerrain(310 ,1 , "roughtwo");
            $this->terrain->addTerrain(311 ,1 , "roughtwo");
            $this->terrain->addTerrain(210 ,1 , "roughtwo");
            $this->terrain->addTerrain(111 ,1 , "roughtwo");
            $this->terrain->addTerrain(211 ,1 , "roughtwo");
            $this->terrain->addTerrain(312 ,1 , "roughtwo");
            $this->terrain->addTerrain(212 ,1 , "roughtwo");
            $this->terrain->addTerrain(112 ,1 , "roughtwo");
            $this->terrain->addTerrain(113 ,1 , "roughtwo");
            $this->terrain->addTerrain(629 ,1 , "roughtwo");
            $this->terrain->addTerrain(1523 ,1 , "roughtwo");
            $this->terrain->addTerrain(1622 ,1 , "roughtwo");
            $this->terrain->addTerrain(1623 ,1 , "roughtwo");
            $this->terrain->addTerrain(1723 ,1 , "roughtwo");
            $this->terrain->addTerrain(1722 ,1 , "roughtwo");
            $this->terrain->addTerrain(1724 ,1 , "roughtwo");
            $this->terrain->addTerrain(1823 ,1 , "roughtwo");
            $this->terrain->addTerrain(1822 ,1 , "roughtwo");
            $this->terrain->addTerrain(1923 ,1 , "roughtwo");
            $this->terrain->addTerrain(1824 ,1 , "roughtwo");
            $this->terrain->addTerrain(2323 ,1 , "roughtwo");
            $this->terrain->addTerrain(2422 ,1 , "roughtwo");
            $this->terrain->addTerrain(2423 ,1 , "roughtwo");
            $this->terrain->addTerrain(2523 ,1 , "roughtwo");
            $this->terrain->addTerrain(2522 ,1 , "roughtwo");
            $this->terrain->addTerrain(2622 ,1 , "roughtwo");
            $this->terrain->addTerrain(2617 ,1 , "roughtwo");
            $this->terrain->addTerrain(2618 ,1 , "roughtwo");
            $this->terrain->addTerrain(2619 ,1 , "roughtwo");
            $this->terrain->addTerrain(2718 ,1 , "roughtwo");
            $this->terrain->addTerrain(2719 ,1 , "roughtwo");
            $this->terrain->addTerrain(2720 ,1 , "roughtwo");
            $this->terrain->addTerrain(2819 ,1 , "roughtwo");
            $this->terrain->addTerrain(2818 ,1 , "roughtwo");
            $this->terrain->addTerrain(2918 ,1 , "roughtwo");
            $this->terrain->addTerrain(2919 ,1 , "roughtwo");
            $this->terrain->addTerrain(3516 ,1 , "roughtwo");
            $this->terrain->addTerrain(3615 ,1 , "roughtwo");
            $this->terrain->addTerrain(3515 ,1 , "roughtwo");
            $this->terrain->addTerrain(3614 ,1 , "roughtwo");
            $this->terrain->addTerrain(3514 ,1 , "roughtwo");
            $this->terrain->addTerrain(4130 ,1 , "roughtwo");
            $this->terrain->addTerrain(4129 ,1 , "roughtwo");
            $this->terrain->addTerrain(6030 ,1 , "roughtwo");
            $this->terrain->addTerrain(5930 ,1 , "roughtwo");
            $this->terrain->addTerrain(6029 ,1 , "roughtwo");
            $this->terrain->addTerrain(6028 ,1 , "roughtwo");
            $this->terrain->addTerrain(5929 ,1 , "roughtwo");
            $this->terrain->addTerrain(5828 ,1 , "roughtwo");
            $this->terrain->addTerrain(5928 ,1 , "roughtwo");
            $this->terrain->addTerrain(6027 ,1 , "roughtwo");
            $this->terrain->addTerrain(5827 ,1 , "roughtwo");
            $this->terrain->addTerrain(5728 ,1 , "roughtwo");
            $this->terrain->addTerrain(5023 ,1 , "roughtwo");
            $this->terrain->addTerrain(4924 ,1 , "roughtwo");
            $this->terrain->addTerrain(4823 ,1 , "roughtwo");
            $this->terrain->addTerrain(4724 ,1 , "roughtwo");
            $this->terrain->addTerrain(4723 ,1 , "roughtwo");
            $this->terrain->addTerrain(4722 ,1 , "roughtwo");
            $this->terrain->addTerrain(5621 ,1 , "roughtwo");
            $this->terrain->addTerrain(5521 ,1 , "roughtwo");
            $this->terrain->addTerrain(5520 ,1 , "roughtwo");
            $this->terrain->addTerrain(104 ,1 , "blocked");
            $this->terrain->addTerrain(203 ,1 , "blocked");
            $this->terrain->addTerrain(304 ,1 , "blocked");
            $this->terrain->addTerrain(404 ,1 , "blocked");
            $this->terrain->addTerrain(504 ,1 , "blocked");
            $this->terrain->addTerrain(604 ,1 , "blocked");
            $this->terrain->addTerrain(705 ,1 , "blocked");
            $this->terrain->addTerrain(804 ,1 , "blocked");
            $this->terrain->addTerrain(904 ,1 , "blocked");
            $this->terrain->addTerrain(1003 ,1 , "blocked");
            $this->terrain->addTerrain(1104 ,1 , "blocked");
            $this->terrain->addTerrain(803 ,1 , "blocked");
            $this->terrain->addTerrain(802 ,1 , "blocked");
            $this->terrain->addTerrain(902 ,1 , "blocked");
            $this->terrain->addTerrain(1001 ,1 , "blocked");
            $this->terrain->addTerrain(1102 ,1 , "blocked");
            $this->terrain->addTerrain(1202 ,1 , "blocked");
            $this->terrain->addTerrain(1303 ,1 , "blocked");
            $this->terrain->addTerrain(1403 ,1 , "blocked");
            $this->terrain->addTerrain(1503 ,1 , "blocked");
            $this->terrain->addTerrain(1602 ,1 , "blocked");
            $this->terrain->addTerrain(1702 ,1 , "blocked");
            $this->terrain->addTerrain(1802 ,1 , "blocked");
            $this->terrain->addTerrain(1903 ,1 , "blocked");
            $this->terrain->addTerrain(2003 ,1 , "blocked");
            $this->terrain->addTerrain(2004 ,1 , "blocked");
            $this->terrain->addTerrain(2105 ,1 , "blocked");
            $this->terrain->addTerrain(2204 ,1 , "blocked");
            $this->terrain->addTerrain(2305 ,1 , "blocked");
            $this->terrain->addTerrain(2304 ,1 , "blocked");
            $this->terrain->addTerrain(2403 ,1 , "blocked");
            $this->terrain->addTerrain(2504 ,1 , "blocked");
            $this->terrain->addTerrain(2505 ,1 , "blocked");
            $this->terrain->addTerrain(2605 ,1 , "blocked");
            $this->terrain->addTerrain(2606 ,1 , "blocked");
            $this->terrain->addTerrain(2607 ,1 , "blocked");
            $this->terrain->addTerrain(2508 ,1 , "blocked");
            $this->terrain->addTerrain(2407 ,1 , "blocked");
            $this->terrain->addTerrain(2408 ,1 , "blocked");
            $this->terrain->addTerrain(2509 ,1 , "blocked");
            $this->terrain->addTerrain(2609 ,1 , "blocked");
            $this->terrain->addTerrain(2709 ,1 , "blocked");
            $this->terrain->addTerrain(2808 ,1 , "blocked");
            $this->terrain->addTerrain(2908 ,1 , "blocked");
            $this->terrain->addTerrain(2907 ,1 , "blocked");
            $this->terrain->addTerrain(3006 ,1 , "blocked");
            $this->terrain->addTerrain(3106 ,1 , "blocked");
            $this->terrain->addTerrain(3205 ,1 , "blocked");
            $this->terrain->addTerrain(3305 ,1 , "blocked");
            $this->terrain->addTerrain(3304 ,1 , "blocked");
            $this->terrain->addTerrain(3403 ,1 , "blocked");
            $this->terrain->addTerrain(3504 ,1 , "blocked");
            $this->terrain->addTerrain(3604 ,1 , "blocked");
            $this->terrain->addTerrain(3705 ,1 , "blocked");
            $this->terrain->addTerrain(3706 ,1 , "blocked");
            $this->terrain->addTerrain(3806 ,1 , "blocked");
            $this->terrain->addTerrain(3907 ,1 , "blocked");
            $this->terrain->addTerrain(4007 ,1 , "blocked");
            $this->terrain->addTerrain(4107 ,1 , "blocked");
            $this->terrain->addTerrain(4206 ,1 , "blocked");
            $this->terrain->addTerrain(4306 ,1 , "blocked");
            $this->terrain->addTerrain(4406 ,1 , "blocked");
            $this->terrain->addTerrain(4506 ,1 , "blocked");
            $this->terrain->addTerrain(4605 ,1 , "blocked");
            $this->terrain->addTerrain(4705 ,1 , "blocked");
            $this->terrain->addTerrain(4805 ,1 , "blocked");
            $this->terrain->addTerrain(4905 ,1 , "blocked");
            $this->terrain->addTerrain(5004 ,1 , "blocked");
            $this->terrain->addTerrain(5104 ,1 , "blocked");
            $this->terrain->addTerrain(5204 ,1 , "blocked");
            $this->terrain->addTerrain(5304 ,1 , "blocked");
            $this->terrain->addTerrain(5403 ,1 , "blocked");
            $this->terrain->addTerrain(5503 ,1 , "blocked");
            $this->terrain->addTerrain(5502 ,1 , "blocked");
            $this->terrain->addTerrain(5501 ,1 , "blocked");
            $this->terrain->addTerrain(1008 ,1 , "road");
            $this->terrain->addTerrain(1007 ,2 , "road");
            $this->terrain->addTerrain(1007 ,1 , "road");
            $this->terrain->addTerrain(1006 ,2 , "road");
            $this->terrain->addTerrain(1006 ,1 , "road");
            $this->terrain->addTerrain(1005 ,2 , "road");
            $this->terrain->addTerrain(1005 ,1 , "road");
            $this->terrain->addTerrain(1004 ,2 , "road");
            $this->terrain->addTerrain(1009 ,1 , "road");
            $this->terrain->addTerrain(1008 ,2 , "road");
            $this->terrain->addTerrain(1009 ,2 , "road");
            $this->terrain->addTerrain(1010 ,1 , "road");
            $this->terrain->addTerrain(1111 ,4 , "road");
            $this->terrain->addTerrain(1210 ,3 , "road");
            $this->terrain->addTerrain(1111 ,3 , "road");
            $this->terrain->addTerrain(1011 ,1 , "road");
            $this->terrain->addTerrain(1011 ,3 , "road");
            $this->terrain->addTerrain(912 ,3 , "road");
            $this->terrain->addTerrain(912 ,1 , "road");
            $this->terrain->addTerrain(812 ,1 , "road");
            $this->terrain->addTerrain(812 ,3 , "road");
            $this->terrain->addTerrain(713 ,1 , "road");
            $this->terrain->addTerrain(713 ,3 , "road");
            $this->terrain->addTerrain(613 ,1 , "road");
            $this->terrain->addTerrain(514 ,1 , "road");
            $this->terrain->addTerrain(613 ,3 , "road");
            $this->terrain->addTerrain(514 ,3 , "road");
            $this->terrain->addTerrain(414 ,1 , "road");
            $this->terrain->addTerrain(414 ,3 , "road");
            $this->terrain->addTerrain(315 ,1 , "road");
            $this->terrain->addTerrain(315 ,3 , "road");
            $this->terrain->addTerrain(215 ,1 , "road");
            $this->terrain->addTerrain(215 ,3 , "road");
            $this->terrain->addTerrain(216 ,4 , "road");
            $this->terrain->addTerrain(216 ,1 , "road");
            $this->terrain->addTerrain(317 ,1 , "road");
            $this->terrain->addTerrain(317 ,4 , "road");
            $this->terrain->addTerrain(417 ,4 , "road");
            $this->terrain->addTerrain(417 ,1 , "road");
            $this->terrain->addTerrain(518 ,4 , "road");
            $this->terrain->addTerrain(518 ,1 , "road");
            $this->terrain->addTerrain(618 ,4 , "road");
            $this->terrain->addTerrain(719 ,4 , "road");
            $this->terrain->addTerrain(618 ,1 , "road");
            $this->terrain->addTerrain(719 ,1 , "road");
            $this->terrain->addTerrain(819 ,4 , "road");
            $this->terrain->addTerrain(819 ,1 , "road");
            $this->terrain->addTerrain(920 ,4 , "road");
            $this->terrain->addTerrain(920 ,1 , "road");
            $this->terrain->addTerrain(1020 ,4 , "road");
            $this->terrain->addTerrain(1020 ,1 , "road");
            $this->terrain->addTerrain(1121 ,4 , "road");
            $this->terrain->addTerrain(1121 ,1 , "road");
            $this->terrain->addTerrain(1221 ,4 , "road");
            $this->terrain->addTerrain(1221 ,1 , "road");
            $this->terrain->addTerrain(1221 ,2 , "road");
            $this->terrain->addTerrain(1222 ,1 , "road");
            $this->terrain->addTerrain(1222 ,2 , "road");
            $this->terrain->addTerrain(1223 ,1 , "road");
            $this->terrain->addTerrain(1223 ,2 , "road");
            $this->terrain->addTerrain(1224 ,1 , "road");
            $this->terrain->addTerrain(1224 ,2 , "road");
            $this->terrain->addTerrain(1225 ,1 , "road");
            $this->terrain->addTerrain(1326 ,4 , "road");
            $this->terrain->addTerrain(1326 ,1 , "road");
            $this->terrain->addTerrain(1426 ,4 , "road");
            $this->terrain->addTerrain(1426 ,1 , "road");
            $this->terrain->addTerrain(1527 ,4 , "road");
            $this->terrain->addTerrain(1527 ,1 , "road");
            $this->terrain->addTerrain(1627 ,4 , "road");
            $this->terrain->addTerrain(1627 ,1 , "road");
            $this->terrain->addTerrain(1728 ,4 , "road");
            $this->terrain->addTerrain(1728 ,1 , "road");
            $this->terrain->addTerrain(1827 ,3 , "road");
            $this->terrain->addTerrain(1827 ,1 , "road");
            $this->terrain->addTerrain(1927 ,3 , "road");
            $this->terrain->addTerrain(1927 ,1 , "road");
            $this->terrain->addTerrain(2027 ,4 , "road");
            $this->terrain->addTerrain(2027 ,1 , "road");
            $this->terrain->addTerrain(2128 ,4 , "road");
            $this->terrain->addTerrain(2227 ,3 , "road");
            $this->terrain->addTerrain(2227 ,1 , "road");
            $this->terrain->addTerrain(2327 ,3 , "road");
            $this->terrain->addTerrain(2327 ,1 , "road");
            $this->terrain->addTerrain(2426 ,3 , "road");
            $this->terrain->addTerrain(2426 ,3 , "wadi");
            $this->terrain->addTerrain(2426 ,1 , "road");
            $this->terrain->addTerrain(2526 ,3 , "road");
            $this->terrain->addTerrain(2526 ,1 , "road");
            $this->terrain->addTerrain(2625 ,3 , "road");
            $this->terrain->addReinforceZone(4708,'A');
            $this->terrain->addReinforceZone(4807,'A');
            $this->terrain->addReinforceZone(4806,'A');
            $this->terrain->addTerrain(4806 ,1 , "road");
            $this->terrain->addReinforceZone(4706,'A');
            $this->terrain->addTerrain(4706 ,1 , "road");
            $this->terrain->addReinforceZone(4707,'A');
            $this->terrain->addReinforceZone(4606,'A');
            $this->terrain->addTerrain(4606 ,1 , "road");
            $this->terrain->addReinforceZone(4607,'A');
            $this->terrain->addReinforceZone(4608,'A');
            $this->terrain->addReinforceZone(4609,'A');
            $this->terrain->addReinforceZone(4510,'A');
            $this->terrain->addReinforceZone(4511,'A');
            $this->terrain->addReinforceZone(4410,'A');
            $this->terrain->addReinforceZone(4310,'A');
            $this->terrain->addReinforceZone(4210,'A');
            $this->terrain->addReinforceZone(4111,'A');
            $this->terrain->addReinforceZone(4010,'A');
            $this->terrain->addReinforceZone(3910,'A');
            $this->terrain->addReinforceZone(3909,'A');
            $this->terrain->addReinforceZone(3908,'A');
            $this->terrain->addTerrain(3908 ,1 , "road");
            $this->terrain->addReinforceZone(3405,'A');
            $this->terrain->addTerrain(3405 ,1 , "town");
            $this->terrain->addReinforceZone(3505,'A');
            $this->terrain->addTerrain(3505 ,1 , "town");
            $this->terrain->addReinforceZone(4008,'A');
            $this->terrain->addTerrain(4008 ,1 , "road");
            $this->terrain->addReinforceZone(4009,'A');
            $this->terrain->addReinforceZone(4110,'A');
            $this->terrain->addReinforceZone(4209,'A');
            $this->terrain->addReinforceZone(4309,'A');
            $this->terrain->addReinforceZone(4408,'A');
            $this->terrain->addReinforceZone(4508,'A');
            $this->terrain->addReinforceZone(4507,'A');
            $this->terrain->addTerrain(4507 ,1 , "road");
            $this->terrain->addReinforceZone(4407,'A');
            $this->terrain->addTerrain(4407 ,1 , "road");
            $this->terrain->addTerrain(4307 ,1 , "town");
            $this->terrain->addReinforceZone(4307,'A');
            $this->terrain->addReinforceZone(4207,'A');
            $this->terrain->addTerrain(4207 ,1 , "road");
            $this->terrain->addReinforceZone(4108,'A');
            $this->terrain->addTerrain(4108 ,1 , "road");
            $this->terrain->addReinforceZone(4109,'A');
            $this->terrain->addReinforceZone(4308,'A');
            $this->terrain->addReinforceZone(4208,'A');
            $this->terrain->addReinforceZone(5319,'A');
            $this->terrain->addTerrain(5319 ,1 , "secondaryroad");
            $this->terrain->addReinforceZone(5318,'A');
            $this->terrain->addTerrain(5318 ,1 , "secondaryroad");
            $this->terrain->addReinforceZone(5317,'A');
            $this->terrain->addTerrain(5317 ,1 , "secondaryroad");
            $this->terrain->addReinforceZone(5416,'A');
            $this->terrain->addReinforceZone(5217,'A');
            $this->terrain->addReinforceZone(5117,'A');
            $this->terrain->addReinforceZone(5016,'A');
            $this->terrain->addReinforceZone(4916,'A');
            $this->terrain->addTerrain(4916 ,1 , "road");
            $this->terrain->addReinforceZone(4915,'A');
            $this->terrain->addReinforceZone(5014,'A');
            $this->terrain->addReinforceZone(5114,'A');
            $this->terrain->addReinforceZone(5214,'A');
            $this->terrain->addTerrain(5214 ,1 , "town");
            $this->terrain->addReinforceZone(5314,'A');
            $this->terrain->addTerrain(5314 ,1 , "road");
            $this->terrain->addReinforceZone(5414,'A');
            $this->terrain->addReinforceZone(5415,'A');
            $this->terrain->addReinforceZone(5315,'A');
            $this->terrain->addTerrain(5315 ,1 , "secondaryroad");
            $this->terrain->addReinforceZone(5316,'A');
            $this->terrain->addTerrain(5316 ,1 , "secondaryroad");
            $this->terrain->addReinforceZone(5216,'A');
            $this->terrain->addReinforceZone(5215,'A');
            $this->terrain->addReinforceZone(5115,'A');
            $this->terrain->addTerrain(5115 ,1 , "road");
            $this->terrain->addReinforceZone(5116,'A');
            $this->terrain->addReinforceZone(5015,'A');
            $this->terrain->addTerrain(5015 ,1 , "road");
            $this->terrain->addReinforceZone(5404,'B');
            $this->terrain->addTerrain(5404 ,1 , "road");
            $this->terrain->addReinforceZone(5405,'B');
            $this->terrain->addReinforceZone(5406,'B');
            $this->terrain->addReinforceZone(5407,'B');
            $this->terrain->addReinforceZone(5408,'B');
            $this->terrain->addReinforceZone(5504,'B');
            $this->terrain->addTerrain(5504 ,1 , "road");
            $this->terrain->addReinforceZone(5505,'B');
            $this->terrain->addReinforceZone(5506,'B');
            $this->terrain->addReinforceZone(5507,'B');
            $this->terrain->addReinforceZone(5508,'B');
            $this->terrain->addReinforceZone(5509,'B');
            $this->terrain->addReinforceZone(5608,'B');
            $this->terrain->addReinforceZone(5607,'B');
            $this->terrain->addReinforceZone(5606,'B');
            $this->terrain->addReinforceZone(5605,'B');
            $this->terrain->addReinforceZone(5604,'B');
            $this->terrain->addReinforceZone(5603,'B');
            $this->terrain->addTerrain(5603 ,1 , "road");
            $this->terrain->addReinforceZone(5602,'B');
            $this->terrain->addReinforceZone(5601,'B');
            $this->terrain->addReinforceZone(5701,'B');
            $this->terrain->addReinforceZone(5702,'B');
            $this->terrain->addReinforceZone(5703,'B');
            $this->terrain->addTerrain(5703 ,1 , "road");
            $this->terrain->addReinforceZone(5704,'B');
            $this->terrain->addReinforceZone(5705,'B');
            $this->terrain->addReinforceZone(5706,'B');
            $this->terrain->addReinforceZone(5707,'B');
            $this->terrain->addReinforceZone(5708,'B');
            $this->terrain->addReinforceZone(5709,'B');
            $this->terrain->addReinforceZone(5808,'B');
            $this->terrain->addTerrain(5808 ,1 , "road");
            $this->terrain->addReinforceZone(5807,'B');
            $this->terrain->addTerrain(5807 ,1 , "road");
            $this->terrain->addReinforceZone(5806,'B');
            $this->terrain->addTerrain(5806 ,1 , "road");
            $this->terrain->addReinforceZone(5805,'B');
            $this->terrain->addTerrain(5805 ,1 , "road");
            $this->terrain->addReinforceZone(5804,'B');
            $this->terrain->addTerrain(5804 ,1 , "road");
            $this->terrain->addReinforceZone(5803,'B');
            $this->terrain->addTerrain(5803 ,1 , "road");
            $this->terrain->addReinforceZone(5802,'B');
            $this->terrain->addReinforceZone(5801,'B');
            $this->terrain->addReinforceZone(5901,'B');
            $this->terrain->addReinforceZone(5902,'B');
            $this->terrain->addReinforceZone(5903,'B');
            $this->terrain->addTerrain(5903 ,1 , "town");
            $this->terrain->addReinforceZone(5904,'B');
            $this->terrain->addTerrain(5904 ,1 , "road");
            $this->terrain->addReinforceZone(5905,'B');
            $this->terrain->addReinforceZone(5906,'B');
            $this->terrain->addReinforceZone(5907,'B');
            $this->terrain->addReinforceZone(5908,'B');
            $this->terrain->addReinforceZone(5909,'B');
            $this->terrain->addReinforceZone(6008,'B');
            $this->terrain->addReinforceZone(6007,'B');
            $this->terrain->addReinforceZone(6006,'B');
            $this->terrain->addReinforceZone(6005,'B');
            $this->terrain->addReinforceZone(6004,'B');
            $this->terrain->addReinforceZone(6003,'B');
            $this->terrain->addReinforceZone(6002,'B');
            $this->terrain->addTerrain(6002 ,1 , "road");
            $this->terrain->addReinforceZone(6001,'B');
            $this->terrain->addReinforceZone(5409,'B');
            $this->terrain->addReinforceZone(5510,'B');
            $this->terrain->addReinforceZone(5609,'B');
            $this->terrain->addReinforceZone(5710,'B');
            $this->terrain->addReinforceZone(5809,'B');
            $this->terrain->addTerrain(5809 ,1 , "road");
            $this->terrain->addReinforceZone(5910,'B');
            $this->terrain->addReinforceZone(6009,'B');
            $this->terrain->addReinforceZone(6010,'B');
            $this->terrain->addReinforceZone(5911,'B');
            $this->terrain->addReinforceZone(5810,'B');
            $this->terrain->addTerrain(5810 ,1 , "road");
            $this->terrain->addReinforceZone(5711,'B');
            $this->terrain->addReinforceZone(5610,'B');
            $this->terrain->addReinforceZone(5811,'B');
            $this->terrain->addTerrain(5811 ,1 , "road");
            $this->terrain->addReinforceZone(5912,'B');
            $this->terrain->addTerrain(5912 ,1 , "road");
            $this->terrain->addReinforceZone(6012,'B');
            $this->terrain->addTerrain(6012 ,1 , "road");
            $this->terrain->addReinforceZone(5913,'B');
            $this->terrain->addReinforceZone(6013,'B');
            $this->terrain->addReinforceZone(6025,'B');
            $this->terrain->addTerrain(6025 ,1 , "secondaryroad");
            $this->terrain->addReinforceZone(5925,'B');
            $this->terrain->addTerrain(5925 ,1 , "secondaryroad");
            $this->terrain->addReinforceZone(5824,'B');
            $this->terrain->addTerrain(5824 ,1 , "secondaryroad");
            $this->terrain->addReinforceZone(5825,'B');
            $this->terrain->addReinforceZone(5726,'B');
            $this->terrain->addTerrain(3404 ,1 , "town");
            $this->terrain->addTerrain(2128 ,1 , "town");
            $this->terrain->addReinforceZone(2128,'A');
            $this->terrain->addTerrain(2511 ,1 , "town");
            $this->terrain->addReinforceZone(2511,'A');
            $this->terrain->addTerrain(1210 ,1 , "road");
            $this->terrain->addTerrain(1310 ,3 , "road");
            $this->terrain->addTerrain(1310 ,1 , "road");
            $this->terrain->addTerrain(1409 ,3 , "road");
            $this->terrain->addTerrain(1409 ,1 , "road");
            $this->terrain->addTerrain(1510 ,4 , "road");
            $this->terrain->addTerrain(1510 ,1 , "road");
            $this->terrain->addTerrain(1610 ,4 , "road");
            $this->terrain->addTerrain(1610 ,1 , "road");
            $this->terrain->addTerrain(1710 ,3 , "road");
            $this->terrain->addTerrain(1710 ,1 , "road");
            $this->terrain->addTerrain(1810 ,4 , "road");
            $this->terrain->addTerrain(1810 ,4 , "wadi");
            $this->terrain->addTerrain(1810 ,1 , "road");
            $this->terrain->addTerrain(1911 ,4 , "road");
            $this->terrain->addTerrain(1911 ,1 , "road");
            $this->terrain->addTerrain(2011 ,1 , "road");
            $this->terrain->addTerrain(2011 ,4 , "road");
            $this->terrain->addTerrain(2112 ,4 , "road");
            $this->terrain->addTerrain(2112 ,1 , "road");
            $this->terrain->addTerrain(2211 ,3 , "road");
            $this->terrain->addTerrain(2211 ,1 , "road");
            $this->terrain->addTerrain(2311 ,3 , "road");
            $this->terrain->addTerrain(2311 ,1 , "road");
            $this->terrain->addTerrain(2411 ,4 , "road");
            $this->terrain->addTerrain(2411 ,1 , "road");
            $this->terrain->addTerrain(2511 ,3 , "road");
            $this->terrain->addTerrain(2610 ,3 , "road");
            $this->terrain->addTerrain(2610 ,1 , "road");
            $this->terrain->addTerrain(2710 ,3 , "road");
            $this->terrain->addTerrain(2710 ,1 , "road");
            $this->terrain->addTerrain(2809 ,3 , "road");
            $this->terrain->addTerrain(2809 ,1 , "road");
            $this->terrain->addTerrain(2909 ,3 , "road");
            $this->terrain->addTerrain(2909 ,1 , "road");
            $this->terrain->addTerrain(3008 ,3 , "road");
            $this->terrain->addTerrain(3008 ,1 , "road");
            $this->terrain->addTerrain(3007 ,2 , "road");
            $this->terrain->addTerrain(3007 ,1 , "road");
            $this->terrain->addTerrain(3107 ,3 , "road");
            $this->terrain->addTerrain(3107 ,1 , "road");
            $this->terrain->addTerrain(3206 ,3 , "road");
            $this->terrain->addTerrain(3206 ,1 , "road");
            $this->terrain->addTerrain(3306 ,3 , "road");
            $this->terrain->addTerrain(3306 ,1 , "road");
            $this->terrain->addTerrain(3405 ,3 , "road");
            $this->terrain->addTerrain(3605 ,4 , "road");
            $this->terrain->addTerrain(3605 ,1 , "road");
            $this->terrain->addTerrain(3605 ,2 , "road");
            $this->terrain->addTerrain(3606 ,1 , "road");
            $this->terrain->addTerrain(3707 ,4 , "road");
            $this->terrain->addTerrain(3707 ,1 , "road");
            $this->terrain->addTerrain(3807 ,4 , "road");
            $this->terrain->addTerrain(3807 ,1 , "road");
            $this->terrain->addTerrain(3908 ,4 , "road");
            $this->terrain->addTerrain(4008 ,4 , "road");
            $this->terrain->addTerrain(4108 ,3 , "road");
            $this->terrain->addTerrain(4207 ,3 , "road");
            $this->terrain->addTerrain(4307 ,3 , "road");
            $this->terrain->addTerrain(4407 ,4 , "road");
            $this->terrain->addTerrain(4507 ,3 , "road");
            $this->terrain->addTerrain(4606 ,3 , "road");
            $this->terrain->addTerrain(4706 ,3 , "road");
            $this->terrain->addTerrain(4706 ,3 , "wadi");
            $this->terrain->addTerrain(4806 ,4 , "road");
            $this->terrain->addTerrain(4906 ,3 , "road");
            $this->terrain->addTerrain(4906 ,3 , "wadi");
            $this->terrain->addTerrain(4906 ,1 , "road");
            $this->terrain->addTerrain(5005 ,3 , "road");
            $this->terrain->addTerrain(5005 ,1 , "road");
            $this->terrain->addTerrain(5105 ,3 , "road");
            $this->terrain->addTerrain(5105 ,1 , "road");
            $this->terrain->addTerrain(5205 ,4 , "road");
            $this->terrain->addTerrain(5205 ,1 , "road");
            $this->terrain->addTerrain(5305 ,3 , "road");
            $this->terrain->addTerrain(5305 ,1 , "road");
            $this->terrain->addTerrain(5404 ,3 , "road");
            $this->terrain->addTerrain(5504 ,3 , "road");
            $this->terrain->addTerrain(5603 ,3 , "road");
            $this->terrain->addTerrain(5703 ,3 , "road");
            $this->terrain->addTerrain(5803 ,4 , "road");
            $this->terrain->addTerrain(5903 ,3 , "road");
            $this->terrain->addTerrain(6002 ,3 , "road");
            $this->terrain->addTerrain(5903 ,2 , "road");
            $this->terrain->addTerrain(5904 ,3 , "road");
            $this->terrain->addTerrain(5804 ,2 , "road");
            $this->terrain->addTerrain(5805 ,2 , "road");
            $this->terrain->addTerrain(5806 ,2 , "road");
            $this->terrain->addTerrain(5807 ,2 , "road");
            $this->terrain->addTerrain(5808 ,2 , "road");
            $this->terrain->addTerrain(5809 ,2 , "road");
            $this->terrain->addTerrain(5810 ,2 , "road");
            $this->terrain->addTerrain(5912 ,4 , "road");
            $this->terrain->addTerrain(6012 ,4 , "road");
            $this->terrain->addTerrain(5811 ,3 , "road");
            $this->terrain->addTerrain(5712 ,1 , "road");
            $this->terrain->addTerrain(5712 ,3 , "road");
            $this->terrain->addTerrain(5612 ,1 , "road");
            $this->terrain->addTerrain(5612 ,3 , "road");
            $this->terrain->addTerrain(5513 ,1 , "road");
            $this->terrain->addTerrain(5513 ,3 , "road");
            $this->terrain->addTerrain(5413 ,1 , "road");
            $this->terrain->addTerrain(5413 ,3 , "road");
            $this->terrain->addTerrain(5314 ,3 , "road");
            $this->terrain->addTerrain(5214 ,3 , "road");
            $this->terrain->addTerrain(5115 ,3 , "road");
            $this->terrain->addTerrain(5015 ,3 , "road");
            $this->terrain->addTerrain(4916 ,3 , "road");
            $this->terrain->addTerrain(4816 ,1 , "road");
            $this->terrain->addTerrain(4816 ,3 , "road");
            $this->terrain->addTerrain(4717 ,1 , "road");
            $this->terrain->addTerrain(4717 ,3 , "road");
            $this->terrain->addTerrain(4617 ,1 , "road");
            $this->terrain->addTerrain(4617 ,3 , "road");
            $this->terrain->addTerrain(4518 ,3 , "road");
            $this->terrain->addTerrain(4518 ,1 , "road");
            $this->terrain->addTerrain(4418 ,1 , "road");
            $this->terrain->addTerrain(4418 ,3 , "road");
            $this->terrain->addTerrain(4319 ,1 , "road");
            $this->terrain->addTerrain(4319 ,3 , "road");
            $this->terrain->addTerrain(4219 ,1 , "road");
            $this->terrain->addTerrain(4219 ,3 , "road");
            $this->terrain->addTerrain(4120 ,1 , "road");
            $this->terrain->addTerrain(4120 ,3 , "road");
            $this->terrain->addTerrain(4020 ,1 , "road");
            $this->terrain->addReinforceZone(4020,'A');
            $this->terrain->addTerrain(4020 ,2 , "road");
            $this->terrain->addTerrain(4021 ,1 , "road");
            $this->terrain->addTerrain(4021 ,2 , "road");
            $this->terrain->addTerrain(4022 ,1 , "road");
            $this->terrain->addTerrain(4022 ,2 , "road");
            $this->terrain->addTerrain(4023 ,1 , "road");
            $this->terrain->addTerrain(4023 ,2 , "road");
            $this->terrain->addTerrain(4024 ,1 , "road");
            $this->terrain->addReinforceZone(4024,'A');
            $this->terrain->addTerrain(4024 ,3 , "road");
            $this->terrain->addTerrain(3925 ,1 , "road");
            $this->terrain->addTerrain(3925 ,3 , "road");
            $this->terrain->addTerrain(3825 ,1 , "road");
            $this->terrain->addTerrain(3825 ,4 , "road");
            $this->terrain->addTerrain(3725 ,1 , "road");
            $this->terrain->addTerrain(3725 ,3 , "road");
            $this->terrain->addTerrain(3625 ,1 , "road");
            $this->terrain->addTerrain(3625 ,4 , "road");
            $this->terrain->addTerrain(3525 ,1 , "road");
            $this->terrain->addTerrain(3525 ,3 , "road");
            $this->terrain->addTerrain(3425 ,1 , "road");
            $this->terrain->addTerrain(3425 ,4 , "road");
            $this->terrain->addTerrain(3325 ,1 , "road");
            $this->terrain->addTerrain(3325 ,3 , "road");
            $this->terrain->addTerrain(3225 ,1 , "road");
            $this->terrain->addTerrain(3225 ,4 , "road");
            $this->terrain->addTerrain(3125 ,1 , "road");
            $this->terrain->addTerrain(3125 ,3 , "road");
            $this->terrain->addTerrain(3025 ,1 , "road");
            $this->terrain->addTerrain(3025 ,4 , "road");
            $this->terrain->addTerrain(2925 ,1 , "road");
            $this->terrain->addTerrain(2925 ,4 , "road");
            $this->terrain->addTerrain(2824 ,1 , "road");
            $this->terrain->addTerrain(2824 ,3 , "road");
            $this->terrain->addTerrain(2725 ,1 , "road");
            $this->terrain->addTerrain(2725 ,3 , "road");
            $this->terrain->addTerrain(2625 ,1 , "road");
            $this->terrain->addTerrain(809 ,4 , "wadi");
            $this->terrain->addTerrain(709 ,2 , "wadi");
            $this->terrain->addTerrain(710 ,4 , "wadi");
            $this->terrain->addTerrain(609 ,2 , "wadi");
            $this->terrain->addTerrain(610 ,4 , "wadi");
            $this->terrain->addTerrain(610 ,3 , "wadi");
            $this->terrain->addTerrain(611 ,4 , "wadi");
            $this->terrain->addTerrain(511 ,2 , "wadi");
            $this->terrain->addTerrain(1613 ,3 , "wadi");
            $this->terrain->addTerrain(1614 ,4 , "wadi");
            $this->terrain->addTerrain(1614 ,3 , "wadi");
            $this->terrain->addTerrain(1615 ,4 , "wadi");
            $this->terrain->addTerrain(1615 ,3 , "wadi");
            $this->terrain->addTerrain(1616 ,4 , "wadi");
            $this->terrain->addTerrain(1616 ,3 , "wadi");
            $this->terrain->addTerrain(1616 ,2 , "wadi");
            $this->terrain->addTerrain(1717 ,3 , "wadi");
            $this->terrain->addTerrain(1718 ,4 , "wadi");
            $this->terrain->addTerrain(1718 ,3 , "wadi");
            $this->terrain->addTerrain(1719 ,4 , "wadi");
            $this->terrain->addTerrain(1719 ,3 , "wadi");
            $this->terrain->addTerrain(122 ,2 , "wadi");
            $this->terrain->addTerrain(222 ,4 , "wadi");
            $this->terrain->addTerrain(221 ,2 , "wadi");
            $this->terrain->addTerrain(322 ,4 , "wadi");
            $this->terrain->addTerrain(321 ,2 , "wadi");
            $this->terrain->addTerrain(321 ,2 , "secondaryroad");
            $this->terrain->addTerrain(421 ,3 , "wadi");
            $this->terrain->addTerrain(421 ,2 , "wadi");
            $this->terrain->addTerrain(522 ,4 , "wadi");
            $this->terrain->addTerrain(521 ,2 , "wadi");
            $this->terrain->addTerrain(621 ,3 , "wadi");
            $this->terrain->addTerrain(621 ,2 , "wadi");
            $this->terrain->addTerrain(1810 ,3 , "wadi");
            $this->terrain->addTerrain(1811 ,4 , "wadi");
            $this->terrain->addTerrain(1811 ,3 , "wadi");
            $this->terrain->addTerrain(1812 ,4 , "wadi");
            $this->terrain->addTerrain(1812 ,3 , "wadi");
            $this->terrain->addTerrain(1812 ,2 , "wadi");
            $this->terrain->addTerrain(1913 ,3 , "wadi");
            $this->terrain->addTerrain(1914 ,4 , "wadi");
            $this->terrain->addTerrain(1914 ,3 , "wadi");
            $this->terrain->addTerrain(1914 ,2 , "wadi");
            $this->terrain->addTerrain(2014 ,4 , "wadi");
            $this->terrain->addTerrain(2013 ,2 , "wadi");
            $this->terrain->addTerrain(2114 ,3 , "wadi");
            $this->terrain->addTerrain(2114 ,2 , "wadi");
            $this->terrain->addTerrain(2214 ,4 , "wadi");
            $this->terrain->addTerrain(2213 ,2 , "wadi");
            $this->terrain->addTerrain(2314 ,4 , "wadi");
            $this->terrain->addTerrain(2314 ,3 , "wadi");
            $this->terrain->addTerrain(1917 ,2 , "wadi");
            $this->terrain->addTerrain(2017 ,3 , "wadi");
            $this->terrain->addTerrain(2018 ,4 , "wadi");
            $this->terrain->addTerrain(2018 ,3 , "wadi");
            $this->terrain->addTerrain(2019 ,4 , "wadi");
            $this->terrain->addTerrain(2019 ,3 , "wadi");
            $this->terrain->addTerrain(2020 ,4 , "wadi");
            $this->terrain->addTerrain(2224 ,4 , "wadi");
            $this->terrain->addTerrain(2224 ,3 , "wadi");
            $this->terrain->addTerrain(2224 ,2 , "wadi");
            $this->terrain->addTerrain(2325 ,3 , "wadi");
            $this->terrain->addTerrain(2325 ,2 , "wadi");
            $this->terrain->addTerrain(2425 ,3 , "wadi");
            $this->terrain->addTerrain(2426 ,4 , "wadi");
            $this->terrain->addTerrain(2426 ,2 , "wadi");
            $this->terrain->addTerrain(2527 ,3 , "wadi");
            $this->terrain->addTerrain(2528 ,4 , "wadi");
            $this->terrain->addTerrain(2528 ,3 , "wadi");
            $this->terrain->addTerrain(2529 ,4 , "wadi");
            $this->terrain->addTerrain(4422 ,2 , "wadi");
            $this->terrain->addTerrain(4422 ,3 , "wadi");
            $this->terrain->addTerrain(4322 ,2 , "wadi");
            $this->terrain->addTerrain(4322 ,3 , "wadi");
            $this->terrain->addTerrain(4221 ,2 , "wadi");
            $this->terrain->addTerrain(4221 ,3 , "wadi");
            $this->terrain->addTerrain(4121 ,2 , "wadi");
            $this->terrain->addTerrain(3918 ,4 , "wadi");
            $this->terrain->addTerrain(3917 ,2 , "wadi");
            $this->terrain->addTerrain(4017 ,4 , "wadi");
            $this->terrain->addTerrain(4016 ,2 , "wadi");
            $this->terrain->addTerrain(4117 ,3 , "wadi");
            $this->terrain->addTerrain(4117 ,2 , "wadi");
            $this->terrain->addTerrain(4217 ,4 , "wadi");
            $this->terrain->addTerrain(4216 ,3 , "wadi");
            $this->terrain->addTerrain(4216 ,4 , "wadi");
            $this->terrain->addTerrain(4215 ,3 , "wadi");
            $this->terrain->addTerrain(4511 ,2 , "wadi");
            $this->terrain->addTerrain(4611 ,4 , "wadi");
            $this->terrain->addTerrain(4610 ,3 , "wadi");
            $this->terrain->addTerrain(4610 ,4 , "wadi");
            $this->terrain->addTerrain(4609 ,2 , "wadi");
            $this->terrain->addTerrain(4710 ,4 , "wadi");
            $this->terrain->addTerrain(4709 ,3 , "wadi");
            $this->terrain->addTerrain(4709 ,4 , "wadi");
            $this->terrain->addTerrain(4708 ,3 , "wadi");
            $this->terrain->addTerrain(4708 ,4 , "wadi");
            $this->terrain->addTerrain(4707 ,3 , "wadi");
            $this->terrain->addTerrain(4707 ,4 , "wadi");
            $this->terrain->addTerrain(4907 ,4 , "wadi");
            $this->terrain->addTerrain(4907 ,3 , "wadi");
            $this->terrain->addTerrain(4908 ,4 , "wadi");
            $this->terrain->addTerrain(4807 ,2 , "wadi");
            $this->terrain->addTerrain(4808 ,4 , "wadi");
            $this->terrain->addTerrain(4708 ,2 , "wadi");
            $this->terrain->addTerrain(2005 ,1 , "trail");
            $this->terrain->addTerrain(2005 ,3 , "trail");
            $this->terrain->addTerrain(1906 ,3 , "trail");
            $this->terrain->addTerrain(1806 ,3 , "trail");
            $this->terrain->addTerrain(1707 ,2 , "trail");
            $this->terrain->addTerrain(2221 ,3 , "trail");
            $this->terrain->addTerrain(2122 ,2 , "trail");
            $this->terrain->addTerrain(2123 ,2 , "trail");
            $this->terrain->addTerrain(2124 ,1 , "trail");
            $this->terrain->addTerrain(2221 ,1 , "trail");
            $this->terrain->addTerrain(1708 ,1 , "trail");
            $this->terrain->addTerrain(107 ,1 , "roughone");
            $this->terrain->addTerrain(107 ,1 , "secondaryroad");
            $this->terrain->addTerrain(206 ,3 , "secondaryroad");
            $this->terrain->addTerrain(306 ,3 , "secondaryroad");
            $this->terrain->addTerrain(405 ,3 , "secondaryroad");
            $this->terrain->addTerrain(506 ,4 , "secondaryroad");
            $this->terrain->addTerrain(606 ,4 , "secondaryroad");
            $this->terrain->addTerrain(606 ,1 , "secondaryroad");
            $this->terrain->addTerrain(706 ,3 , "secondaryroad");
            $this->terrain->addTerrain(706 ,1 , "secondaryroad");
            $this->terrain->addTerrain(805 ,3 , "secondaryroad");
            $this->terrain->addTerrain(805 ,1 , "secondaryroad");
            $this->terrain->addTerrain(905 ,3 , "secondaryroad");
            $this->terrain->addTerrain(905 ,1 , "secondaryroad");
            $this->terrain->addTerrain(1005 ,4 , "secondaryroad");
            $this->terrain->addTerrain(229 ,2 , "secondaryroad");
            $this->terrain->addTerrain(329 ,3 , "secondaryroad");
            $this->terrain->addTerrain(429 ,4 , "secondaryroad");
            $this->terrain->addTerrain(529 ,3 , "secondaryroad");
            $this->terrain->addTerrain(528 ,2 , "secondaryroad");
            $this->terrain->addTerrain(627 ,3 , "secondaryroad");
            $this->terrain->addTerrain(627 ,4 , "secondaryroad");
            $this->terrain->addTerrain(527 ,4 , "secondaryroad");
            $this->terrain->addTerrain(425 ,2 , "secondaryroad");
            $this->terrain->addTerrain(425 ,1 , "secondaryroad");
            $this->terrain->addTerrain(425 ,4 , "secondaryroad");
            $this->terrain->addTerrain(325 ,1 , "secondaryroad");
            $this->terrain->addTerrain(324 ,2 , "secondaryroad");
            $this->terrain->addTerrain(324 ,1 , "secondaryroad");
            $this->terrain->addTerrain(323 ,2 , "secondaryroad");
            $this->terrain->addTerrain(323 ,1 , "secondaryroad");
            $this->terrain->addTerrain(322 ,2 , "secondaryroad");
            $this->terrain->addTerrain(322 ,1 , "secondaryroad");
            $this->terrain->addTerrain(321 ,1 , "secondaryroad");
            $this->terrain->addTerrain(320 ,2 , "secondaryroad");
            $this->terrain->addTerrain(320 ,1 , "secondaryroad");
            $this->terrain->addTerrain(319 ,2 , "secondaryroad");
            $this->terrain->addTerrain(319 ,1 , "secondaryroad");
            $this->terrain->addTerrain(318 ,2 , "secondaryroad");
            $this->terrain->addTerrain(318 ,1 , "secondaryroad");
            $this->terrain->addTerrain(317 ,2 , "secondaryroad");
            $this->terrain->addTerrain(728 ,4 , "secondaryroad");
            $this->terrain->addTerrain(828 ,4 , "secondaryroad");
            $this->terrain->addTerrain(929 ,4 , "secondaryroad");
            $this->terrain->addTerrain(1028 ,3 , "secondaryroad");
            $this->terrain->addTerrain(1028 ,1 , "secondaryroad");
            $this->terrain->addTerrain(1129 ,4 , "secondaryroad");
            $this->terrain->addTerrain(1129 ,1 , "secondaryroad");
            $this->terrain->addTerrain(1228 ,3 , "secondaryroad");
            $this->terrain->addTerrain(1228 ,1 , "secondaryroad");
            $this->terrain->addTerrain(1328 ,3 , "secondaryroad");
            $this->terrain->addTerrain(1328 ,1 , "secondaryroad");
            $this->terrain->addTerrain(1427 ,3 , "secondaryroad");
            $this->terrain->addTerrain(1427 ,1 , "secondaryroad");
            $this->terrain->addTerrain(1527 ,3 , "secondaryroad");
            $this->terrain->addTerrain(4124 ,3 , "secondaryroad");
            $this->terrain->addTerrain(4124 ,1 , "secondaryroad");
            $this->terrain->addTerrain(4224 ,4 , "secondaryroad");
            $this->terrain->addTerrain(4224 ,1 , "secondaryroad");
            $this->terrain->addTerrain(4325 ,4 , "secondaryroad");
            $this->terrain->addTerrain(4325 ,1 , "secondaryroad");
            $this->terrain->addTerrain(4425 ,4 , "secondaryroad");
            $this->terrain->addTerrain(4425 ,1 , "secondaryroad");
            $this->terrain->addTerrain(4526 ,4 , "secondaryroad");
            $this->terrain->addTerrain(4526 ,1 , "secondaryroad");
            $this->terrain->addTerrain(4626 ,4 , "secondaryroad");
            $this->terrain->addTerrain(4626 ,1 , "secondaryroad");
            $this->terrain->addTerrain(4727 ,4 , "secondaryroad");
            $this->terrain->addTerrain(4727 ,1 , "secondaryroad");
            $this->terrain->addTerrain(4826 ,3 , "secondaryroad");
            $this->terrain->addTerrain(4826 ,1 , "secondaryroad");
            $this->terrain->addTerrain(4927 ,4 , "secondaryroad");
            $this->terrain->addTerrain(4927 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5027 ,4 , "secondaryroad");
            $this->terrain->addTerrain(5027 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5128 ,4 , "secondaryroad");
            $this->terrain->addTerrain(5128 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5227 ,3 , "secondaryroad");
            $this->terrain->addTerrain(5227 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5327 ,3 , "secondaryroad");
            $this->terrain->addTerrain(5327 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5326 ,2 , "secondaryroad");
            $this->terrain->addTerrain(5326 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5325 ,2 , "secondaryroad");
            $this->terrain->addTerrain(5325 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5324 ,2 , "secondaryroad");
            $this->terrain->addTerrain(5324 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5323 ,2 , "secondaryroad");
            $this->terrain->addTerrain(5423 ,3 , "secondaryroad");
            $this->terrain->addTerrain(5423 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5523 ,3 , "secondaryroad");
            $this->terrain->addTerrain(5523 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5623 ,4 , "secondaryroad");
            $this->terrain->addTerrain(5724 ,4 , "secondaryroad");
            $this->terrain->addTerrain(5824 ,4 , "secondaryroad");
            $this->terrain->addTerrain(5925 ,4 , "secondaryroad");
            $this->terrain->addTerrain(6025 ,4 , "secondaryroad");
            $this->terrain->addTerrain(5323 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5322 ,2 , "secondaryroad");
            $this->terrain->addTerrain(5322 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5321 ,2 , "secondaryroad");
            $this->terrain->addTerrain(5321 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5320 ,2 , "secondaryroad");
            $this->terrain->addTerrain(5320 ,1 , "secondaryroad");
            $this->terrain->addTerrain(5319 ,2 , "secondaryroad");
            $this->terrain->addTerrain(5318 ,2 , "secondaryroad");
            $this->terrain->addTerrain(5317 ,2 , "secondaryroad");
            $this->terrain->addTerrain(5316 ,2 , "secondaryroad");
            $this->terrain->addTerrain(5315 ,2 , "secondaryroad");
            $this->terrain->addTerrain(5314 ,2 , "secondaryroad");
            $this->terrain->addTerrain(3505 ,3 , "road");
            $this->terrain->addReinforceZone(4509,'A');
            $this->terrain->addReinforceZone(4409,'A');
            $this->terrain->addTerrain(2711 ,4 , "secondaryroad");
            $this->terrain->addTerrain(2711 ,1 , "secondaryroad");
            $this->terrain->addTerrain(2811 ,4 , "secondaryroad");
            $this->terrain->addTerrain(2811 ,1 , "secondaryroad");
            $this->terrain->addTerrain(2912 ,4 , "secondaryroad");
            $this->terrain->addTerrain(2912 ,1 , "secondaryroad");
            $this->terrain->addTerrain(3012 ,4 , "secondaryroad");
            $this->terrain->addTerrain(3012 ,1 , "secondaryroad");
            $this->terrain->addTerrain(3113 ,4 , "secondaryroad");
            $this->terrain->addTerrain(3113 ,1 , "secondaryroad");
            $this->terrain->addTerrain(3113 ,2 , "secondaryroad");
            $this->terrain->addTerrain(3114 ,1 , "secondaryroad");
            $this->terrain->addTerrain(3114 ,2 , "secondaryroad");
            $this->terrain->addTerrain(3115 ,1 , "secondaryroad");
            $this->terrain->addTerrain(3115 ,2 , "secondaryroad");
            $this->terrain->addTerrain(3116 ,1 , "secondaryroad");
            $this->terrain->addTerrain(3216 ,4 , "secondaryroad");
            $this->terrain->addTerrain(3216 ,1 , "secondaryroad");
            $this->terrain->addTerrain(3317 ,4 , "secondaryroad");
            $this->terrain->addTerrain(3417 ,4 , "secondaryroad");
            $this->terrain->addTerrain(3518 ,4 , "secondaryroad");
            $this->terrain->addTerrain(3518 ,1 , "secondaryroad");
            $this->terrain->addTerrain(3618 ,4 , "secondaryroad");
            $this->terrain->addTerrain(3618 ,1 , "secondaryroad");
            $this->terrain->addTerrain(3719 ,4 , "secondaryroad");
            $this->terrain->addTerrain(3719 ,1 , "secondaryroad");
            $this->terrain->addTerrain(3819 ,4 , "secondaryroad");
            $this->terrain->addTerrain(3819 ,1 , "secondaryroad");
            $this->terrain->addTerrain(3920 ,4 , "secondaryroad");
            $this->terrain->addTerrain(3920 ,1 , "secondaryroad");
            $this->terrain->addTerrain(4020 ,4 , "secondaryroad");
            // end terrain data ----------------------------------------

        }
    }
}
